# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    wget https://golang.org/dl/go1.19.3.linux-amd64.tar.gz
    sudo rm -rf /usr/local/go
    sudo tar -C /usr/local -xzf go1.19.3.linux-amd64.tar.gz
    echo 'export GOROOT=/usr/local/go' >> ~/.bashrc
    echo 'export GOPATH=$HOME/go' >> ~/.bashrc
    echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$PATH' >> ~/.bashrc 
    source ~/.bashrc
  displayName: 'Set up the Go workspace'
- script: |
    go version
  displayName: 'GO Version'
- script: |
    go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
  displayName: 'Install Nuclei'
- script: |
    nuclei -u https://example.com
  displayName: 'Run Nuclei'