# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
# SET UP GO
trigger:
- nuclei-scan

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.19.3'
- script: |
    go version
  displayName: 'Go Version'
- script: |
    git clone https://github.com/projectdiscovery/nuclei.git; \
    cd nuclei/v2/cmd/nuclei; \
    go build; \
    mv nuclei /usr/local/bin/; \
    nuclei -version;
    nuclei -h
    echo  '$(System.DefaultWorkingDirectory)'
    dir
  displayName: 'Install Nuclei'
- script: |
    git clone https://github.com/projectdiscovery/nuclei-templates.git
    echo  '$(System.DefaultWorkingDirectory)'
    dir
  displayName: 'Download Nuclei Template'
- script: |
    nuclei -u https://example.com -t nuclei-templates/ -o nuclei-report/nuclei-report.txt
  displayName: 'Run Nuclei'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
